/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.builder.ui;

import com.builder.model.Project;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;

/**
 *
 * @author Nikola
 */
public class ExamplesViewer extends JPanel {

    int topLeft_x = 0;
    int topLeft_y = 0;
    private Project proj;
    final private Boolean[] isSegmentsEnabled;

    /**
     * Creates new form ExamplesViewer
     */
    public ExamplesViewer(Boolean isSegmentsEnabled[]) {

        initComponents();
        this.isSegmentsEnabled = isSegmentsEnabled;
    }

    public void setVisibleSpace(int x, int y) {

        if (proj == null) {
            return;
        }

        BufferedImage img = proj.getDrawable(false);

        if (img == null) {
            return;
        }

        if (x != -1) {
            double span_x = img.getWidth() - getWidth();

            double new_x = (double) x / 90.0 * span_x;

            topLeft_x = (int) new_x;
        }
        if (y != -1) {
            double spax_y = img.getHeight() - getHeight();

            double new_y = (double) y / 90.0 * spax_y;

            topLeft_y = (int) new_y;
        }
    }

    @Override
    protected void paintComponent(Graphics g) {

        super.paintComponent(g);

        drawImage((Graphics2D) g);

    }

    public void setProject(Project prj) {
        this.proj = prj;
    }

    private void drawImage(Graphics2D g) {

        if (proj == null) {
            return;
        }

        if (proj.getDrawable(isSegmentsEnabled[0]) == null) {
            return;
        }
        
        g.drawImage(
                proj.getDrawable(isSegmentsEnabled[0]),
                0,
                0,
                getWidth(),
                getHeight(),
                topLeft_x,
                topLeft_y,
                topLeft_x + getWidth(),
                topLeft_y + getHeight(),
                null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
